---
title: "COVID19_Project"
author: "Julian, Nabih, Nathan, and Yehya"
date: 02-10-2020
output:
  github_document:
    toc: true
---

```{r setup}
library(tidyverse)
```

*Background*:


# Getting the Data
<!------------------------------------------------------>
##The GDP data can be substituted for GapMinder
```{r load-covid-data}
url_covid <- "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
## Set the filenames of the data to download
filename_covid <- "./data/covid_countries.csv"
filename_gdp <- "./data/gdp_countries.csv"
## Download the data locally
curl::curl_download(
        url_covid,
        destfile = filename_covid
)
## Loads the downloaded csv
df_covid <- read_csv(filename_covid) %>% select(iso_code, location, date, total_cases, total_deaths, population)
df_gdp <- read_csv(filename_gdp, skip = 1)
# summary(df_covid)
# summary(df_gdp)
```
```{r}
gdp_covid <- df_gdp %>% select("iso_code", "location", "date", "total_cases_per_million", "total_deaths_per_million", "median_age", "gdp_per_capita") %>%
  merge(df_covid) %>%
  drop_na()
gdp_covid

```

# Join the Data
<!-- -------------------------------------------------- -->
##Hopefully well be able to join the data using the ISO code, if not we can use the country name and see what problems that may bring

```{r}
gdp_covid %>% 
  ggplot(aes(
    x = gdp_per_capita,
    y = total_cases_per_million
  )) +
  geom_point() +
  labs(
    x = "GDP per Capita",
    y = "Total Cases per Million",
    title = "Cases per Million People vs GDP per Capita"
  )
```

# Work on the Data
<!-- -------------------------------------------------- -->

# Conclusion
<!-- -------------------------------------------------- -->
